name: geox-new
channels:
  - conda-forge
  - nodefaults
  - bioconda

dependencies:
  - atlite=0.3.0
  - cartopy
  - gdal
  - geopandas
  - geopy
  - matplotlib
  - numpy
  - openpyxl
  - pandas=2.1.4
  - pip
  - pypsa=0.26.0
  - python
  - shapely=1.8.4
  - snakemake
  - xarray 
